### ISSUE TITLE
White space created at the page top when menu activated

### ISSUE THREAD

**Issue by AdityaVT** [zebedeeLewis/conquer_rebuild#21]
White space is created at the top of the page when the hamburger menu is activated on smaller screen widths. It seems that the page as a whole shifts down when the menu is active. 

Steps to reproduce issue:
-Reduce the screen width till the hamburger menu pops up
-Scroll to the top of the page 
-Activate the menu

This causes the whole page to shift down while the menu is activated.

**Comment by zebedeeLewis** [comment]
I seems that sticky positioned elements reserve their initial space in the document flow. That's what was causing the problem. Thank you for pointing it out.

pull request #22

**Comment by AdityaVT** [comment]
Glad you solved it.
